/****************************************************************
 cia.H
 Copyright (C)2015 William H. Majoros (martiandna@gmail.com).
 This is OPEN SOURCE SOFTWARE governed by the Gnu General Public
 License (GPL) version 3, as described at www.opensource.org.
 ****************************************************************/
#ifndef INCL_cia_H
#define INCL_cia_H
#include "BOOM/String.H"
#include "BOOM/Sequence.H"
#include "BOOM/Set.H"
#include "BOOM/SmartPointer.H"
#include "SignalType.H"
#include "ContentType.H"
#include "Labeling.H"
#include "LabelMatrix.H"


#endif
