/****************************************************************
 ReferenceAnnotation.H
 Copyright (C)2015 William H. Majoros (martiandna@gmail.com).
 This is OPEN SOURCE SOFTWARE governed by the Gnu General Public
 License (GPL) version 3, as described at www.opensource.org.
 ****************************************************************/
#ifndef INCL_ReferenceAnnotation_H
#define INCL_ReferenceAnnotation_H
#include <iostream>
using namespace std;
using namespace BOOM;


class ReferenceAnnotation {
public:
  ReferenceAnnotation();
};

#endif

